version: '3.7'

services:
  crawler_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always

    networks:
      - backend
    

  crawler_frontend:
    build:
      context: nodejs-server
      dockerfile: Dockerfile
    ports:
          - "80:8000"
    restart: always
    depends_on:
      - crawler_backend
    networks:
      - frontend

networks:
  backend:
  frontend: